#My properties File
#Mon May 04 08:33:25 IST 2026
Project\ Name=Phoenix Test Automation Framework
BASE_URI=http\://64.227.160.186\:9000/v1
java\ version=17.0.2
Env=qa
Operating\ system=Windows 10
Name=jatin
